### ISSUE TITLE
[FORGE] Crash on dropped Modded armor / item rendering

### ISSUE THREAD

**Issue by JimBimBum** [Adrenix/Nostalgic-Tweaks#100]
## Version Information

Minecraft Version: 1.20.1
Forge Version: 47.3.10
Nostalgic Tweaks Version: 2.0.0-beta.903

> Item renderer causing crash

## Crash Report
>
[crash-2024-11-25_01.52.27-client.txt](https://github.com/user-attachments/files/17903982/crash-2024-11-25_01.52.27-client.txt)
[crash-2024-11-25_05.34.47-client.txt](https://github.com/user-attachments/files/17903983/crash-2024-11-25_05.34.47-client.txt)

## Bug Context
>"first time i tossed my boyfriend a helmet as i was giving him a set." "second i killed a mob that was wearing modded armor it must've dropped a piece." when dropping an item specifically another mods' armor piece, it just crashes. this it was mekanism's "Refined Obsidian Leggings" but last time was steel helmet from ad astra. this also happened when i killed a zombie and the game crashed on both of our games but both logs are from me.

adding my mod list just incase it's needed context.
[modlist.txt](https://github.com/user-attachments/files/17904129/modlist.txt)

**Comment by JimBimBum** [comment]
possible temp fix _and i'm guessing_ is going into the config and changing these settings

 "old2dItems": false, #was true
    "old2dColors": false,
    "old2dRendering": false, #was true

**Comment by Adrenix** [comment]
This is an issue with the Destroy mod. Their [UniversalArmorTrimItemOverrides#resolve](https://github.com/petrolpark/Destroy/issues/520) method needs to handle possible `null` values for the `ClientLevel` parameter since vanilla has marked it as `@Nullable`.
