### ISSUE TITLE
[FABRIC] Game crashes when Sodium is present

### ISSUE THREAD

**Issue by LOKO-brasil** [Adrenix/Nostalgic-Tweaks#101]
## Version Information

Minecraft Version: 1.20.1
Fabric Loader Version: 0.16.9
Fabric API Version: 0.92.2
Nostalgic Tweaks Version: 2.0.0-beta.903

## Describe the Bug

Minecraft crashes while launching when Sodium is present, tested with and without it. 

## Crash Report

[crash-2024-12-12_19.18.52-client.txt](https://github.com/user-attachments/files/18118189/crash-2024-12-12_19.18.52-client.txt)

## Bug Context

N/A

## Screenshots

N/A

**Comment by Adrenix** [comment]
You have a very old version of Sodium installed. Update Sodium to 0.5.11 for N.T beta.903.
