### ISSUE TITLE
Crash on startup with More Block Predicates mod

### ISSUE THREAD

**Issue by bwilliance** [Adrenix/Nostalgic-Tweaks#11]
Game crashes on startup when mod is used with More Block Predicates mod.
https://github.com/omoflop/MoreBlockPredicates

Crash report:
[crash-2022-07-09_03.57.08-client.txt](https://github.com/Adrenix/Nostalgic-Tweaks/files/9078224/crash-2022-07-09_03.57.08-client.txt)

Crash message from Minecraft launcher:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'indium'!
Exit Code: -1

**Comment by Adrenix** [comment]
This issue is now fixed in `v1.0.5 (1.18.2)` and `v1.1.1 (1.19)` and is available on both [CurseForge](https://www.curseforge.com/minecraft/mc-mods/nostalgic-tweaks) and [Modrinth](https://modrinth.com/mod/nostalgic-tweaks).
