### ISSUE TITLE
[FORGE] [v1.0.4] Spooky crash -Registry Object not present

### ISSUE THREAD

**Issue by Cixon** [Adrenix/Nostalgic-Tweaks#13]
## Describe the Bug
Client Crash.

**desc:** client crashes when teleporting to a new dimension.

## Crash Report
[crash-2022-07-24_17.50.50-client.txt](https://github.com/Adrenix/Nostalgic-Tweaks/files/9176791/crash-2022-07-24_17.50.50-client.txt)

## Latest Log
[latest.log](https://github.com/Adrenix/Nostalgic-Tweaks/files/9176794/latest.log)

**Comment by Adrenix** [comment]
Thank you for submitting this report! I'll have it fixed in the next version. 👍

**Comment by Cixon** [comment]
> Thank you for submitting this report! I'll have it fixed in the next version. 👍

Thanks! forgot to mention this is for 1.18.2

**Comment by Adrenix** [comment]
This issue is now fixed in v1.0.5 and is available on both [CurseForge](https://www.curseforge.com/minecraft/mc-mods/nostalgic-tweaks) and [Modrinth](https://modrinth.com/mod/nostalgic-tweaks).
