### ISSUE TITLE
[FABRIC] Animals always drop one non-stackable food item.

### ISSUE THREAD

**Issue by LiLPNuTTy** [Adrenix/Nostalgic-Tweaks#14]
## Description
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

[  I've noticed when playing with food stacking disabled that all animals always drop 1 of each non-stackable item instead of a random number. Pigs used to drop 0–2 pork chops when killed before release 1.3.1, so animals should be dropping random amounts of food instead of one every time.  ]

**Comment by Adrenix** [comment]
I'll take a look into why this is happening. Thanks for letting me know!

**Comment by Adrenix** [comment]
Resolved in 1.19-2.0.0-Beta.04
