### ISSUE TITLE
Experience/Hunger labels don't respect hud hiding option when current screen isn't null

### ISSUE THREAD

**Issue by forkiesassds** [Adrenix/Nostalgic-Tweaks#15]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.19
Nostalgic Tweaks Version: 2.0-beta3

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

When the hud is hidden the Experience/Hunger labels are hidden, but when you go to the pause screen they are not hidden

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

N/A

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

N/A

## Screenshots
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/54495659/183086750-8859798c-2284-4b04-b2fb-9ea5cbd64fb2.png)

**Comment by Adrenix** [comment]
I think some other vanilla Minecraft HUD elements do this too with F1 active while going into the pause screen. I'll look into this and add an extra conditional to prevent this for the text HUD overlay tweaks. 👍

**Comment by Adrenix** [comment]
Resolved in 1.19-2.0.0-Beta.04
