### ISSUE TITLE
[FABRIC] Crashes with Extended Clouds 1.2.0

### ISSUE THREAD

**Issue by lunarbunten** [Adrenix/Nostalgic-Tweaks#18]
## Version Information
Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.9
Fabric API Version: 0.60.0
Nostalgic Tweaks Version: 1.2.0

## Describe the Bug
Crashes randomly ingame.

## Crash Report
[Link](https://gist.github.com/lunarbunten/a0cfe54b54af906ac52be27b72c00a09)

## Bug Context
Joined a world with Extended Clouds and Nostalgia Tweaks, and the game crashed after a few seconds.

## Screenshots
N/A

**Comment by Adrenix** [comment]
This issue is now resolved in the most recent release of the mod for 1.18.2, 1.19, and 1.19.2. Thank you for submitting this report!
