### ISSUE TITLE
[FABRIC] Stuck on world loading screen

### ISSUE THREAD

**Issue by InsaanNotFound** [Adrenix/Nostalgic-Tweaks#20]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.9
Fabric API Version: 0.60.0
Nostalgic Tweaks Version: 1.2.2
## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

When loading into a world game gets stuck after "Building terrain" endlessly and refuses to actually render the world.

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

No errors in the logs. 

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

When loading into the world.

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by Adrenix** [comment]
Thanks for the report. Could you please provide a list of the mods installed for this instance? It sounds like a mod conflict, but without an error this will require a bit more research before I can resolve this problem.

**Comment by CitizenFoffie** [comment]
This is almost 100% an issue with 2 mods that edit world gen.

**Comment by InsaanNotFound** [comment]
Hey, I just woke up. I am testing each setting one by one, whenever the game will actually load into the world I will let you know which option actually caused the game to behave like that. I may be able to pinpoint mods causing it to happen too.
