### ISSUE TITLE
[FORGE] Old Lighting Rendering displays light levels 4 to 1 as light level 0.

### ISSUE THREAD

**Issue by Thombias** [Adrenix/Nostalgic-Tweaks#21]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.18.2
Forge Version: 40.1.80
Nostalgic Tweaks Version: 1.0.7

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

The title describes pretty much the whole thing. I've noticed that the lighting coming from a block source of light ends very harshly. I then disabled the old lighting rendering to see if it was the case with vanilla lighting, which it wasn't as you can see in the screenshots below.

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

N/a

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

The first screenshot displays vanilla lighting at night time with lighting coming from a lantern. The second one is is the same except with old lighting rendering enabled. The third screenshot shows the F3 menu while standing on a block that should have a block lighting of 4, but it looks the exact same as light levels 3 to 0. The fourth screenshot is just the bug at display from a farther distance with the brightness set to 100%. In every other screenshot it was set to 0%.

## Screenshots
![2022-10-09_13 27 24](https://user-images.githubusercontent.com/46842890/194754593-8905213c-2e19-47b1-89c3-a099d41b90d6.png)
![2022-10-09_13 27 37](https://user-images.githubusercontent.com/46842890/194754598-04ed83ba-0703-4b30-ae0e-4b87c9ca425c.png)
![2022-10-09_13 27 55](https://user-images.githubusercontent.com/46842890/194754610-cb628886-f729-46e2-8590-0b55365e4390.png)
![2022-10-09_13 28 05](https://user-images.githubusercontent.com/46842890/194754615-e7d78303-3d98-4adc-b4d2-693d3bb73718.png)

**Comment by Thombias** [comment]
I forgot to mention something else in here: This issue appears only when sky lighting meets block lighting. If light is coming from a light source for example underground where there's no sky lighting at all, it will look perfectly fine.

**Comment by Adrenix** [comment]
Thank you for the screenshots and extra detail, much appreciated!

**Comment by Adrenix** [comment]
After further research, it seems the way the mod renders light now is how old light rendering looked before Minecraft Beta 1.8.

I'll make a new old light color tweak so users can disable the old light rendering but keep the old colors. The mod is getting close to the anticipated 2.0 release, so I will add in the new tweak for 2.0 builds. 👍

**Comment by Adrenix** [comment]
This issue should be fixed in the most recent beta release.
