### ISSUE TITLE
[FABRIC] startup crash with Optifabric

### ISSUE THREAD

**Issue by MexaHuka** [Adrenix/Nostalgic-Tweaks#22]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.10
Fabric API Version: 0.64.0
Nostalgic Tweaks Version: 1.2.2

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

Startup crash with OptiFabric

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

https://gist.githubusercontent.com/MexaHuka/83421ed2ea32f0a8047e20becd24f2cd/raw/e124b0d56b4d507699220db8a48faa54443ad6d3/gistfile1.txt

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

Startup crash with OptiFabric

## Screenshots
> If applicable, add screenshots to help explain your problem.
![Screenshot_13](https://user-images.githubusercontent.com/95777781/198901817-1854a935-11be-4cde-9d20-aaaa89f8e9b5.png)

**Comment by Adrenix** [comment]
Nostalgic Tweaks (v1) is **incompatible** with optifabric. If you want to use optifabric with Nostalgic Tweaks then you need to use version **2.0.0-Beta.07+** which can be downloaded at the mod's [discord](https://discord.gg/jWdfVh3) server.

**Comment by StereoMadnessss** [comment]
🤣
