### ISSUE TITLE
[FORGE] (Mod Incompatibility) phantom lighting with Starlight and Old Light Rendering enabled

### ISSUE THREAD

**Issue by zebjamb** [Adrenix/Nostalgic-Tweaks#23]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.18.2
Forge Version: 40.1.84
Nostalgic Tweaks Version: 1.0.7
Starlight Version: 1.0.2+forge.546ae87

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

When using the Old Light Rendering with Starlight Installed, placing and breaking light blocks will often times result in the the light lingering until the chunk the torch was placed in is updated. 

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

n/a

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

n/a

## Screenshots
> If applicable, add screenshots to help explain your problem.
![Screenshot 2022-11-13 181331](https://user-images.githubusercontent.com/55518408/201549973-99613959-4638-4b24-aa83-7dc89e3e6e94.png)
![Screenshot 2022-11-13 181545](https://user-images.githubusercontent.com/55518408/201549978-70d5eb5b-4ef2-4d1f-8cde-b11018f29949.png)

**Comment by Adrenix** [comment]
This issue should be fixed in v2.0. If not, then please reopen this issue.
