### ISSUE TITLE
[FABRIC] Old Torch Brightness tweak cannot be loaded

### ISSUE THREAD

**Issue by brine-egg** [Adrenix/Nostalgic-Tweaks#26]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.19.3
Fabric Loader Version: 0.14.17
Fabric API Version: 0.75.1+1.19.3
Nostalgic Tweaks Version: 2.0.0 Beta-8.2

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

The "Old Torch Brightness" tweak has no effect, with the red exclamation mark showing that it has not loaded.

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

N/a

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

It is not caused by mod incompatibility as the issue persists even after removing all mods other than the dependencies (fabric api & architectury), all lighting and torch tweaks have been turned on apart from old classic light rendering.

## Screenshots
> If applicable, add screenshots to help explain your problem.
![2023-03-04_21 15 55](https://user-images.githubusercontent.com/89018140/222898511-ce70c3cc-2d74-4325-88be-97c250ad3460.png)
![2023-03-04_21 18 57](https://user-images.githubusercontent.com/89018140/222898516-44eb35bb-e9fc-426b-8c9e-8e14bd35babd.png)
![2023-03-04_21 19 19](https://user-images.githubusercontent.com/89018140/222898517-d970fba3-012a-4220-aa3d-d039706da83c.png)
![2023-03-04_21 15 09](https://user-images.githubusercontent.com/89018140/222898519-93ec3f87-36ab-4f59-9fba-4bcc7cd0a567.png)

**Comment by Adrenix** [comment]
The latest Fabric API update seems to have broken that tweak. I'll fix this issue and update the Fabric API requirements for the mod in the next commit. 👍

**Comment by brine-egg** [comment]
Nice! Works just fine with latest fabric api now, though not with sodium, I assume that's not fixable due to how sodium changes rendering?
