### ISSUE TITLE
[FABRIC] chest model conflicting with EBE and config for it isn't working properly

### ISSUE THREAD

**Issue by zndrmn** [Adrenix/Nostalgic-Tweaks#27]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.19.3
Fabric Loader Version: 0.14.14
Fabric API Version: 0.75.1
Nostalgic Tweaks Version: [v2.0.0 Beta-8.2](https://modrinth.com/mod/nostalgic-tweaks/version/1.19.3%2Bfabric%2B2.0.0-beta-8.2)

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

Chest models are defaulting to `Old Chest=On` regardless of what was changed in the config (with [EBE](https://modrinth.com/mod/ebe)) 
The original voxel shape stays the same.

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

[**latest.log**](https://gist.github.com/zndrmn/7957e8ae33c4b4f96ae880b4cedbd403#file-latest-log)

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

Conflicting mod, https://modrinth.com/mod/ebe
Works fine without EBE

## Screenshots
> If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/77690119/222951488-1945bd82-6b2a-4eb3-9354-90c98262ee9d.mp4

**Comment by Adrenix** [comment]
This issue is now fixed in v2.0.0 Beta 8.3 for 1.18.2, 1.19.2, and 1.19.4.
