### ISSUE TITLE
[FORGE] [possibly fabric too] Tinyarm render when using Offhand combat

### ISSUE THREAD

**Issue by Cixon** [Adrenix/Nostalgic-Tweaks#28]
Minecraft Version: 1.18.2
[issue may be present in other versions too]

Forge Version: 40.2.1

[NostalgicTweaks-1.18.2-Forge-2.0.0-Beta-8.2](https://www.curseforge.com/minecraft/mc-mods/nostalgic-tweaks/files/4422269)

**Issue:**
When old reequip logic is enabled and Offhandcombat is installed, the players arms are shorted and not available to see unless they are mining.

Mod-link(s):
https://www.curseforge.com/minecraft/mc-mods/off-hand-combat

fabric
https://www.curseforge.com/minecraft/mc-mods/off-hand-combat-fabric

## Screenshots
![image](https://user-images.githubusercontent.com/69068153/222969689-2cdc0fcd-c231-4602-a886-eb058e4d2c8c.png)

**Comment by Adrenix** [comment]
I can't reproduce this issue on beta 8.2 for Forge or Fabric with off hand combat installed. Are there any other mods installed that may be conflicting?
