### ISSUE TITLE
[FORGE] [Possibly Fabric too] Can't climb trapdoors.

### ISSUE THREAD

**Issue by johannesspinnenschreck** [Adrenix/Nostalgic-Tweaks#29]
Vanilla Minecraft added the feature to climb open trapdoors when they're placed above a ladder on the same wall as the ladder.
For some reason this doesn't work with this mod.
![2023-03-07_00 00 17](https://user-images.githubusercontent.com/69090516/223275991-7ffc2f93-1e26-4ef7-becd-25611b86357a.png)

**Comment by Adrenix** [comment]
This issue is now fixed in v2.0.0 Beta 8.3 for 1.18.2, 1.19.2, and 1.19.4.
