### ISSUE TITLE
[FABRIC] 1.19.4 crashes on startup `java.lang.ExceptionInInitializerError`

### ISSUE THREAD

**Issue by zndrmn** [Adrenix/Nostalgic-Tweaks#32]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.19.4
Fabric Loader Version: 0.14.19
Fabric API Version: 0.78.0
Nostalgic Tweaks Version: 2.0.0-Beta-8.3

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

Game crashes on startup

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

[latest.log](https://gist.github.com/zndrmn/119368dae344f95599fc2903af151e05#file-gistfile1-txt)

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

N/A

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by Adrenix** [comment]
This should now be fixed in the latest beta 8.4 release. Thank you for creating this issue!
