### ISSUE TITLE
[FORGE] Compatibility Issue with Aether 1.19.4

### ISSUE THREAD

**Issue by cavy8** [Adrenix/Nostalgic-Tweaks#34]
Can't find the template others used, but:

Version: 1.19.4
2.0.0 beta 8.3

Basically, the issue is that the "old lighting" option, which is on by default, breaks the eternal daytime of the aether. Not sure if compatibility is a concern, but I figure if it's because it's using block light, the assigned block light could still be inferred using alternate what would be the sky light?

It does turn day if you use /time set day, but then time just starts progressing until it's dark again.

**Comment by Adrenix** [comment]
This is now fixed in the latest beta 8.4 release. Thank you for creating this issue!
