### ISSUE TITLE
[FABRIC] 

### ISSUE THREAD

**Issue by ILYFireblade** [Adrenix/Nostalgic-Tweaks#35]
Bro i cant sprint with the slow mod in minecraft.

**Comment by ILYFireblade** [comment]
i cant f1cking sprint with the mod. i think its a setting.

**Comment by FrozenDragon0** [comment]
> Bro i cant sprint with the slow mod in minecraft.

1. This is really not how you make an issue on github, no info given whatsoever nor a proper title.

2. It's a setting that disables sprint.
