### ISSUE TITLE
[FORGE] Can't exit "Texture Packs" menu by clicking "Done"

### ISSUE THREAD

**Issue by dustboxednorth** [Adrenix/Nostalgic-Tweaks#36]
Minecraft Version: 1.19.4
Forge Version: 45.0.49
Nostalgic Tweaks Version: 2.0.0-Beta-8.3

When entering the "Texture Packs" menu on the title screen while `Eye Candy > Interface Candy > Title Screen > Buttons > Old Button Layout` is set to `Beta`, clicking "Done" does nothing and I remain stuck within the resource packs menu.

**Comment by Pankine** [comment]
can confirm this also happens on fabric

**Comment by Adrenix** [comment]
This is now fixed in the latest beta 8.4 release. Thank you for creating this issue!
