### ISSUE TITLE
[FORGE] Crash with vampirism

### ISSUE THREAD

**Issue by MetalKnight56** [Adrenix/Nostalgic-Tweaks#38]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.18.2
Forge Version: 40.2.8
Nostalgic Tweaks Version: forge 2.0.0 beta 0.8.3

## Describe the Bug
> Game crashes everytime i right-click the Altar of Inspiration from Vampirism with a Blood Bottle

## Crash Report
> https://mclo.gs/2vmZkKJ

## Bug Context
> The game crashes, when i try to advance in vampirism, after i right click the altar of inspiration from vampirism my game crashes, that only happens if i have nostalgic tweaks enabled. I've tried playing only with the two mods and my game crashed.

## Screenshots
> N/A

**Comment by MetalKnight56** [comment]
#https://github.com/TeamLapen/Vampirism/issues/1218

**Comment by forkiesassds** [comment]
The mod seems to not define a fill sound at all, and it seems there is no logic to handle a potential case to handle a null sound... Whoops!

**Comment by MetalKnight56** [comment]
> The mod seems to not define a fill sound at all, and it seems there is no logic to handle a potential case to handle a null sound... Whoops!

I don't get it, is there anything i can do to fix this ? Or anything the vampirism developer should do to fix this issue?

**Comment by Adrenix** [comment]
At the moment there isn't anything you can do. I'm unsure if there is an issue the Vampirism developer needs to handle, but for me, it will be an easy fix on my end to handle any `null` sounds.

**Comment by MetalKnight56** [comment]
Thanks for the commit, i'll await for the mod to be build to test it

**Comment by Adrenix** [comment]
I uploaded jars that have the commit to the project's releases. Here is the jar for Forge: https://github.com/Adrenix/Nostalgic-Tweaks/releases/download/v2.0/NostalgicTweaks-1.18.2-Forge-2.0.0-Beta-8.4-Commit-2e0e9b9.jar

**Comment by MetalKnight56** [comment]
> I uploaded jars that have the commit to the project's releases. Here is the jar for Forge: https://github.com/Adrenix/Nostalgic-Tweaks/releases/download/v2.0/NostalgicTweaks-1.18.2-Forge-2.0.0-Beta-8.4-Commit-2e0e9b9.jar

It fixed the issue, just tested it, and its working just fine, thanks for the help dude, I'll let you know if i find any more issues ! :)
