### ISSUE TITLE
[FABRIC] [QUILT] Crash on entering the world

### ISSUE THREAD

**Issue by jucogjucogi** [Adrenix/Nostalgic-Tweaks#39]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.19.4
Fabric Loader Version: quilt 0.19.1
Fabric API Version: qfapi
Nostalgic Tweaks Version: 0.83.0 beta-9

## Describe the Bug

crash on entering the world, console says something about nostalgic_tweaks and getmobcap
## Crash Report
https://mclo.gs/MihVqVz

## Bug Context
crash on entering the world

**Comment by Adrenix** [comment]
This issue is now fixed in the latest beta 8.4 release. Thanks for the crash report!
