### ISSUE TITLE
[FORGE] Controllable mod hunger bar position conflict

### ISSUE THREAD

**Issue by ambient7** [Adrenix/Nostalgic-Tweaks#42]
## Version Information

Minecraft Version: 1.19.4
Forge Version: 45.1.0
Nostalgic Tweaks Version: 2.0.0 Beta 8.4

## Describe the Bug

Hunger bar keeps original (Lower) position after turning on console hotbar setting on controllable mod

## Crash Report

N/a

## Bug Context

Anytime if Controllable's console hotbar is enabled even if all tweaks are disabled

## Screenshots
![2023-08-07_20 25 28](https://github.com/Adrenix/Nostalgic-Tweaks/assets/76193987/11da0e47-d7c8-466d-8577-995514fe2163)

**Comment by TechSupportRed** [comment]
Receiving this same issue

**Comment by MythrilBagels** [comment]
I'm receiving a similar issue, but with the Armour bar since I have the Hunger bar disabled, with the Raised mod same as blammie

**Comment by Adrenix** [comment]
This issue should be resolved in beta 9.
