### ISSUE TITLE
[FABRIC] Classic item damage bar tweak breaks overrides to `Item.getBarColor`

### ISSUE THREAD

**Issue by coyo-t** [Adrenix/Nostalgic-Tweaks#43]
## Version Information
Minecraft Version: 1.20.1
Fabric Loader Version: 0.14.22
Fabric API Version: 0.87.0
Nostalgic Tweaks Version: v2.0.0 Beta 8.4

## Describe the Bug
When using the classic item damage bar colours tweak, items which override damage-bar related methods (Im assuming its `Item.getBarColor`, but might also affect others like `Item.getBarWidth`?) are busted, usually resulting in an entirely empty bar, but sometimes not! sometimes its entirely filled and green, depends.

## Crash Report
N/a

## Screenshots
Tweak disabled.
Four golden shovels, an AE2 Entropy Manipulator, a Tech Reborn Basic Drill, two vanilla bundles, and an AE2 Matter Cannon.
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/22027276/66f9b499-215e-45d4-84fe-543c25afd67c)

Tweak enabled.
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/22027276/3bf21176-f8c0-44f0-80aa-32af529887f4)

AE2's bars always seem to be at the empty stage...
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/22027276/53827def-aac4-4b49-b1b1-4aec5ba4b86a)

...While Tech Reborn's seem to be largely always filled, except for some of the battery items which always appear empty
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/22027276/2ea56b09-9b36-4fac-bd8c-f56efe613059)

Tweak disabled for reference:
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/22027276/1df5cecd-3f5e-423e-9715-e252e38a2cbd)

![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/22027276/f3c0b003-057d-4676-af77-ceeb69191d47)

Edit: Just checked and the old damage bar tweak doesn't even touch `Item.getBarColor` directly as it i guess is just drawing the old-style bar graphics over the modern one?
I think the easiest fix would be to draw the old bar background parts, check if the item type overrides `getBarColor`, and return if it does before drawing the new coloured part. Maybe keep a map of itemtypes that do so too because idk how expensive the reflection is?

**Comment by Adrenix** [comment]
The solution I came up with was checking if the durability bar color matches the expected outcome based on the item's current durability. If it doesn't, then the item is using a special algorithm and that tells N.T to leave the item durability bar color alone. This fix is in beta.902/903. Thank you for submitting this issue!
