### ISSUE TITLE
[FORGE] Compatability Issue with Industrial Foregoing's tanks

### ISSUE THREAD

**Issue by DarkRTA** [Adrenix/Nostalgic-Tweaks#45]
## Version Information

Minecraft Version: 1.19.2
Forge Version: 43.3.0
Nostalgic Tweaks Version: 2.0.0-Beta-8.4
Industrial Foregoing Version: 3.3.2.3

## Describe the Bug
Attempting to use a bucket to add certain fluids into a tank from Industrial Foregoing results in a crash if Nostalgic Tweaks is also installed. This seems to be related to how Nostalgic Tweaks modifies some of the sound code.

## Crash Report
[crash-2023-10-29_12.54.28-client.txt](https://github.com/Adrenix/Nostalgic-Tweaks/files/13198654/crash-2023-10-29_12.54.28-client.txt)

## Video Demonstration

https://github.com/Adrenix/Nostalgic-Tweaks/assets/15368682/1913db59-632c-4d51-b769-47ccb9a6e804

**Comment by Adrenix** [comment]
This should be fixed in beta 9. I'll eventually make a backport fix for this in 1.20.1.
