### ISSUE TITLE
[FORGE] Void Gui crash

### ISSUE THREAD

**Issue by TinyOff** [Adrenix/Nostalgic-Tweaks#46]
## Version Information

Minecraft Version: 1.201
Forge Version: 47.2.0
Nostalgic Tweaks Version: 8.4.1

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

World start up crash

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

n/a

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

Everytime i try to load up a world it crashes due to the void gui

## Screenshots
> If applicable, add screenshots to help explain your problem.
![Cap](https://github.com/Adrenix/Nostalgic-Tweaks/assets/149416266/f2d6bbe5-3625-4d22-b313-516084053e66)
![Capt](https://github.com/Adrenix/Nostalgic-Tweaks/assets/149416266/9c71f673-dfeb-44ae-8774-d21db888bb95)
![4](https://github.com/Adrenix/Nostalgic-Tweaks/assets/149416266/7f37d5b2-bb27-4fe8-9cb3-4e2815d45612)

**Comment by forkiesassds** [comment]
Are you using Optifine? If not then that's an issue with Forge, if you are using Optifine then blame Optifine, not Forge and NOT this mod.

**Comment by Adrenix** [comment]
As mentioned above this issue seems to be caused by Optifine.
