### ISSUE TITLE
[FABRIC] The "Disable Item Tooltips" parameter does not work.

### ISSUE THREAD

**Issue by FitchKrause** [Adrenix/Nostalgic-Tweaks#49]
## Version Information
Minecraft Version: 1.20.1
Fabric Loader Version: 0.15.2
Fabric API Version: 0.91.0
Nostalgic Tweaks Version: 2.0.0 Beta-8.4.1

## Describe the Bug
If you enable the "Disable Item Tooltips" option, the tooltips will continue to be displayed above the items in the inventory.

## Crash Report
N/a

## Bug Context
N/a

## Screenshots
![javaw_p2HHHQsqEc](https://github.com/Adrenix/Nostalgic-Tweaks/assets/52543383/d7159cde-bec1-47e8-8703-802b020603ff)
![javaw_J9Hzkvhxdk](https://github.com/Adrenix/Nostalgic-Tweaks/assets/52543383/df41e71a-baeb-4648-a41b-7dee374426d4)

**Comment by Adrenix** [comment]
Fixed in beta 9.
