### ISSUE TITLE
[FABRIC] "Old Water Lighting" reintroduces smooth water lighting bug with Sodium.

### ISSUE THREAD

**Issue by EpicGamer42069Fortnite** [Adrenix/Nostalgic-Tweaks#50]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.1
Fabric Loader Version: 0.15.1
Fabric API Version: 0.91.0
Nostalgic Tweaks Version: 2.0.0-Beta-8.4.1

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

In Vanilla Minecraft, smooth lighting is bugged and does not work on water.
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/148576913/b0887b46-a5c8-4403-82d4-7d97cebad05d)

With Sodium installed, this bug is fixed.
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/148576913/fce25033-d9b5-473f-b11a-b09748b88c5a)

However, if I install Nostalgic Tweaks along with Sodium, and enable "Old Water Lighting", the bugged water is back.
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/148576913/a0fa9560-a598-4789-9eee-d3d40b0bb77b)

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

N/A

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

Something to note is that some people may prefer having the lighting bug there, since that's how it was in old Minecraft, and some people may prefer having the water lighting smoothed out while still having the old water lighting.

## Screenshots
> If applicable, add screenshots to help explain your problem.

See above.

**Comment by Adrenix** [comment]
There is now a separate toggle for this in beta 9 now. I'll eventually add a backport tweak for 1.20.1. Thank you for the suggestion!

**Comment by Barerock** [comment]
This is not fixed in forge
![image](https://github.com/user-attachments/assets/cea439d4-b5f5-4711-bf4d-e4d517a41157)
![image](https://github.com/user-attachments/assets/1d40f616-61e6-42ef-a0c7-198011c1f9c4)

**Comment by Barerock** [comment]
It was fixed with a previous version of Nostalgic Tweaks, but 902 reintroduces the bug.
