### ISSUE TITLE
[FABRIC] Lighting bug in the overworld

### ISSUE THREAD

**Issue by Zeldaboy14** [Adrenix/Nostalgic-Tweaks#52]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.1
Fabric Loader Version: 0.14.23
Fabric API Version: 0.88
Nostalgic Tweaks Version: 2.0.0

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

When it's night outside, the overworld seems to act fullbright. This wasn't an issue in a earlier version of Nostalgic Tweaks. Grass renders fine for some bizarre reason. Underground also seems to act fine as well, so idk whats going on.

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

n/a

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

n/a

## Screenshots
> If applicable, add screenshots to help explain your problem.
![2024-01-02_00 49 45](https://github.com/Adrenix/Nostalgic-Tweaks/assets/55566323/b5325cea-40b2-47c1-84e4-971312490957)

**Comment by Adrenix** [comment]
Looks like you're using Sodium. Make sure you're using Sodium 0.5 or greater and Nostalgic Tweaks v2.0.0 Beta 8.4.1.

**Comment by Zeldaboy14** [comment]
I'm using Fabric, and Nostalgic Tweaks v2.0.0 Beta 8.4.1. I've not used Sodium at all for mods
