### ISSUE TITLE
[FORGE] Visual Overhaul Incompatibility: Crash on Settings GUI Button Press

### ISSUE THREAD

**Issue by Sarund9** [Adrenix/Nostalgic-Tweaks#53]
```
Minecraft Version: 1.20.1
Forge Version: 47.2.19
Nostalgic Tweaks Version: 2.0.0-Beta-8.4.1
```

## Steps to Reproduce
- Install versions above
- Install Visual Overhaul (5.0.1)
- Load the game, enter the mods screen
- Enter Nostalgic tweaks config screen
- Pressing the Settings button causes a NullPointerException.

## Describe the Bug
Crash on pressing a button on the settings screen if Visual Overhaul is installed.
> java.lang.NullPointerException: Cannot invoke "mod.adrenix.nostalgic.client.config.reflect.TweakClientCache.getValue()" because "this.tweak" is null
> at mod.adrenix.nostalgic.client.config.gui.widget.button.BooleanButton.m_6035_(BooleanButton.java:42) ~[NostalgicTweaks-1.20.1-Forge-2.0.0-Beta-8.4.1.jar%23162!/:?] {re:classloading}
> at eu.midnightdust.visualoverhaul.IconicButtons.init(IconicButtons.java:30) ~[visualoverhaul-forge-5.0.1.jar%23163!/:?] {re:mixin,re:classloading}
> at eu.midnightdust.visualoverhaul.IconicButtons.<init>(IconicButtons.java:27) ~[visualoverhaul-forge-5.0.1.jar%23163!/:?] {re:mixin,re:classloading}

A Visual Overhaul mixin is causing BooleanButton to contain a null TweakClientCache<Boolean> `tweak` member.

## Cause of the bug
VO adds custom Icons to GUI Buttons, they seem to be using Mixins to do so.
I did not test pressing other buttons, but they probably also crash.
Disabling the Button icons in VOs config does not fix the crash (Mixins are not disabled on config settings)

It also shows the "saving chunks" screen bedore crashing, although I don't think that's relevant.

**Comment by Adrenix** [comment]
This should no longer be an issue in beta 9.
