### ISSUE TITLE
[FORGE] The player cannot eat if they have a shield in their offhand with classic food enabled (No hunger and food restore HP)

### ISSUE THREAD

**Issue by Daralexen05** [Adrenix/Nostalgic-Tweaks#54]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.1
Forge Version: Latest release of Forge for 1.20.1
Nostalgic Tweaks Version: NostalgicTweaks-1.20.1-Forge-2.0.0-Beta-8.4.1.jar

## Describe the Bug
The title states it all. Players cannot eat food if they have a shield in their offhand with the classic food system enabled. Players have to unequip their shield to eat. Is this an intended feature or bug? I find it a little annoying, especially since I have this mod installed alongside Sculk Horde, a mod that makes a shield necessary for survival.

**Comment by Adrenix** [comment]
Fixed in beta 9. This will eventually receive a backport fix for 1.20.1.
