### ISSUE TITLE
[FORGE] Server Crashes on Launch

### ISSUE THREAD

**Issue by captinwill** [Adrenix/Nostalgic-Tweaks#60]
## Version Information

Minecraft Version: 1.20.1
Forge Version: forge-1.20.1-47.2.0
Nostalgic Tweaks Version: NostalgicTweaks-1.20.1-Forge-2.0.0-Beta-8.4.1

## Describe the Bug

Server Crashes on Launch

## Crash Report

[crash-2024-03-03_16.46.36-fml.txt](https://github.com/Adrenix/Nostalgic-Tweaks/files/14474694/crash-2024-03-03_16.46.36-fml.txt)

## Bug Context

N/A

## Screenshots
N/A

**Comment by Adrenix** [comment]
Install [Architectury](https://modrinth.com/mod/architectury-api/version/9.2.14+forge). It's a required dependency.
