### ISSUE TITLE
[FABRIC] and [FORGE]

### ISSUE THREAD

**Issue by Mixces** [Adrenix/Nostalgic-Tweaks#61]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.19.x - 1.20.x
This issue also appears in both the Forge and Fabric versions.

## Describe the Bug

Basically, the OLD_DAMAGE_ARMOR_TINT feature works well, HOWEVER, if you were to have an enchanted piece of armor on and then take damage, your armor's enchantment glint would not be showing during that moment of damage.

## The Fix

I also ran into this issue while making the same feature in my mod after being inspired by Nostalgic Tweaks, and well, I actually really like Nostalgic Tweaks, so I feel very inclined to share the fix. In order to fix this, you should replace "getEntityCutoutNoCull" with "getEntityCutoutNoCullZOffset" (taken from yarn mappings). This fixed the issue for me.

## Screenshots
Here are some screenshots for further proof.

In the first screenshot, the glint is clearly missing while taking damage. In the second image, the glint is visibly there whilst taking damage.
![no_glint](https://github.com/Adrenix/Nostalgic-Tweaks/assets/70869960/bdfba805-ff85-485b-b996-0882fe532f6b)
![yes_glint](https://github.com/Adrenix/Nostalgic-Tweaks/assets/70869960/dca60748-152c-43ec-8c85-792c0baa4b67)

**Comment by Adrenix** [comment]
Thanks for pointing that out and sharing the solution! :)

**Comment by Mixces** [comment]
Also sorry if this is weird, but would you mind accepting my discord friend request? We have similar passions for nostalgic Minecraft features and well I think I may be of help in your project 👀

**Comment by Adrenix** [comment]
Fixed in beta 9. This will eventually receive a backport fix for 1.20.1.
