### ISSUE TITLE
[NEO/FORGE][1.20.1] Nostalgic Tweaks breaks cloud fog blending AND obstructs clouds with fog at the same time?

### ISSUE THREAD

**Issue by Wanderer70** [Adrenix/Nostalgic-Tweaks#62]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.1
Forge Version: NeoForge 47.1.101
Nostalgic Tweaks Version: 1.20.1-Forge-2.0.0-Beta-8.4.1

## Describe the Bug

> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

Not sure if the "cloud fog blending" is the correct term, but basically when you have Nostalgic Tweaks installed the clouds won't blend in with the fog. Instead, they will be visible up to the point where the game stops rendering them. In addition to that, clouds seem to be "in" the fog, as their sides are not visible (see screenshots). I have almost every tweak disabled or set to default. The ones active should not be causing any of this. Obviously, I also have Embeddium and other mods installed.

## Screenshots
> If applicable, add screenshots to help explain your problem.

**How it should be:**

![Screenshot (960)](https://github.com/Adrenix/Nostalgic-Tweaks/assets/97387920/228b69d7-0a5b-49e5-af63-363d63c8499a)

**How it is:**

![Screenshot (959)](https://github.com/Adrenix/Nostalgic-Tweaks/assets/97387920/4c3d543c-f58a-402c-9657-b04e5eb87fd3)

**Comment by Adrenix** [comment]
(_As noted in the discussion on discord_) This is a feature of Rubidium/Embeddium. Rubidium is supported for 1.20/.1. Embeddium will be supported 1.20.4 onwards.

**Comment by Wanderer70** [comment]
I thought this could be worked around by modifiying the mods.toml file in NostalgicTweaks\META-INF\ and it actually appears to work. Under [mods."sodium:options"] I changed "mixin.features.render.world.clouds"=false to "mixin.features.render.world.clouds"=true. I am unsure whether this could be considered an actual fix, as I suppose it breaks other stuff (does it?) Anyway, point is, if this is literally the only thing required to fix this issue on 1.20.1, why not make a simple patch update with just this change? Provided that it doesn't break anything else or affect any other tweak. If that's the case sorry for the trouble! :D
