### ISSUE TITLE
[FORGE] Crash with structures generating on server

### ISSUE THREAD

**Issue by Krunchee164** [Adrenix/Nostalgic-Tweaks#63]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.1
Forge Version: 47.2.30
Nostalgic Tweaks Version: 8.4.1

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

if certain structures are attempted to be loaded in a chunk, it will tick the server causing a 'Timed out' error and the server would crash

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

https://gist.github.com/Krunchee164/4a8631b5f50ae16e4ac804820553e0c6

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

loading in a chunk (presumably) with a structure causing the server to crash

**Comment by Adrenix** [comment]
I wasn't able to reproduce this issue, but if it persists in the beta 9 release then please reopen this issue.
