### ISSUE TITLE
[FABRIC] Cannot load all tweaks in "Gameplay" tab and most tweaks in "Animation"

### ISSUE THREAD

**Issue by brine-egg** [Adrenix/Nostalgic-Tweaks#64]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.4
Fabric Loader Version: 0.15.10
Fabric API Version: 0.97.0
Nostalgic Tweaks Version: 2.0.0-Beta-9.0 (commit ea118c8)

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

Most client side tweaks from the "Sound" and "Eye Candy" tabs work just fine, however none of the gameplay/server side changes are applied and they are shown as failed to load in the config menu, same thing for the animation tweaks save for the "Arm Sway Mirror" tweak which is shown as loaded, despite having no noticeable effect.

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

N/a

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

Mod was compiled with Gradle 8.5. Confirmed the issue was not caused by conflicting mods as it persists even after removing all mods besides Fabric API and Architectury.

## Screenshots
> If applicable, add screenshots to help explain your problem.
![2024-04-16_17 49 32](https://github.com/Adrenix/Nostalgic-Tweaks/assets/89018140/f9e895d7-7ece-4a46-847a-32ab735c3a63)
![2024-04-16_17 58 12](https://github.com/Adrenix/Nostalgic-Tweaks/assets/89018140/323bce1a-0859-4f03-8f15-1bd5d63db91b)

**Comment by Adrenix** [comment]
Beta 9 is a complete mod rewrite for 1.20.4 so most of the mod's tweaks are currently not implemented yet. Which is why there are a lot of red traffic lights. :)

I've updated the main branch readme and 1.20.4 branch readme to remove any confusion about the status of 1.20.4.

**Comment by brine-egg** [comment]
> Beta 9 is a complete mod rewrite for 1.20.4 so most of the mod's tweaks are currently not implemented yet. Which is why there are a lot of red traffic lights. :)
> 
> I've updated the main branch readme and 1.20.4 branch readme to remove any confusion about the status of 1.20.4.

Ah, my bad. Didn't realise these features are not added yet. Thanks for the clarification!
