### ISSUE TITLE
[FABRIC] Minecraft crashes on startup with the new beta.

### ISSUE THREAD

**Issue by MonochromeOS** [Adrenix/Nostalgic-Tweaks#65]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.4
Fabric Loader Version: 0.15.10
Fabric API Version: 0.97.0
Nostalgic Tweaks Version: 2.0.0 Beta-9.0-Indev-1

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

Minecraft crashes on startup.

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

https://gist.github.com/MonochromeOS/e416af470ab6a99028453a0be9397808

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

Not much to write here. The game launched perfectly fine before installing, now it doesn't. Assuming this is some kind of mod conflict since it's a beta.

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by Adrenix** [comment]
It seems that the FancyMenu mod loads a screen so early that the game hasn't loaded its options yet which is causing this crash. I updated the in-dev [release page](https://github.com/Adrenix/Nostalgic-Tweaks/releases/tag/v2.0.0-Beta-9-1.20.4-Indev-1) with new 1.1 jars that should patch this issue.
