### ISSUE TITLE
[FABRIC] With Embeddium/Sodium crashes

### ISSUE THREAD

**Issue by seriousfreezing** [Adrenix/Nostalgic-Tweaks#69]
Minecraft Version: 1.20.4
Fabric Loader Version: 0.15.11
Fabric API Version: 0.97.1
Nostalgic Tweaks Version: 2.0.0-Beta-9.0-RC

From what I've tested, the problem stops if you remove Sodium/Embeddium or remove Nostalgic Tweaks. But it does occur when loading chunks.

[crash-2024-06-16_22.15.44-client.txt](https://github.com/user-attachments/files/15860534/crash-2024-06-16_22.15.44-client.txt)

**Comment by Adrenix** [comment]
Turning off `Old Torch Bottom` should prevent this specific crash until a patch is released.
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/15348635/49c1ff11-53f5-42b9-a420-0df68a8f0a0e)

**Comment by Adrenix** [comment]
Fixed in beta 9 release.
