### ISSUE TITLE
Inconsistency with old 2D floating items

### ISSUE THREAD

**Issue by Ghutenshtoff-Industries** [Adrenix/Nostalgic-Tweaks#7]
Some items do not render as 2D items when dropped. In my limited testing it appears to be blocks such as slabs, stairs, trapdoors, pressure plates, buttons, and other transparent blocks. Testing was done with a fresh fabric install with only Nostalgic Tweaks installed.

**Comment by Adrenix** [comment]
I don't recall those blocks rendering in 2D in older versions? Right now I have it setup to where items that can render 2D in the inventory renders in 2D when it is an item entity.

**Comment by Ghutenshtoff-Industries** [comment]
How interesting, you're right. I just checked with older versions and it appears that blocks still render as 3D spinning. My apologies for the confusion, it's been so long.
