### ISSUE TITLE
[FABRIC] Sodium + Ferrite Core Crash Game when Joining World

### ISSUE THREAD

**Issue by Carl-Kabat** [Adrenix/Nostalgic-Tweaks#70]
## Version

Minecraft Version: 1.20.4
Fabric Loader Version: 0.15.11
Fabric API Version: 0.97.1
Nostalgic Tweaks Version: 2.0.0-Beta-9.0-RC

Sodium Version: mc.1.20.4-0.5.8
Ferrite Core Version: 6.0.3-fabric

##  Bug description

Game crashed when joining into a singleplayer world when both Sodium and Ferrite Core are enabled.

## Crash Log

https://gist.github.com/Carl-Kabat/e6a391b33090557a5d136acdebcd1dee

## Bug Context

Crash occurs only when both performance mods are enabled simultaneously.

**Comment by Adrenix** [comment]
This crash it similar to the one reported [here](https://github.com/Adrenix/Nostalgic-Tweaks/issues/69). For now, turning off the `Old Torch Bottom` will prevent the crash until a patch is released.
