### ISSUE TITLE
[FABRIC] Hitbox Outline makes Texture underneath Invisible with Iris enabled

### ISSUE THREAD

**Issue by Carl-Kabat** [Adrenix/Nostalgic-Tweaks#71]
## Version Information

Minecraft : 1.20.4
Fabric : 0.15.11
Fabric API : 0.97.1+1.20.4
Nostalgic Tweaks : 2.0.0-Beta-9.0-RC

Iris: 1.7.1+1.20.4

## Bug
Some blocks' hitbox outlines make texture of said blocks see-through, creating mask-like behavior

## Context
Hitbox Outline must have applied a partial alpha value, works on blocks like Shulker Boxes, Mob Heads, Decorative Pots, etc.
Screenshots below.

## Screenshots
![2024-06-19_03 09 51](https://github.com/Adrenix/Nostalgic-Tweaks/assets/61113001/6f9be431-b04c-4506-ae67-733a4de51152)
![2024-06-19_03 10 51](https://github.com/Adrenix/Nostalgic-Tweaks/assets/61113001/973227cd-ddb3-4420-8a7e-afd58215d5e6)

**Comment by Adrenix** [comment]
Fixed in beta 9 release.
