### ISSUE TITLE
[FABRIC] trident doesn't work while it's raining with riptide (not in a water block)

### ISSUE THREAD

**Issue by NPC-Master3304** [Adrenix/Nostalgic-Tweaks#72]
## Version Information

Minecraft Version: 1.20.4
Fabric Loader Version: 0.15.11
Fabric API Version: 0.97.1
Nostalgic Tweaks Version: 2.0.0 b9.0 RC

## Describe the Bug

key feature not working as intended.

https://github.com/Adrenix/Nostalgic-Tweaks/assets/71358236/339d27c1-13e4-422e-9ce4-72ee04fbc80d

**Comment by Adrenix** [comment]
Fixed in beta 9.
