### ISSUE TITLE
[FABRIC] Tooltip text not visible when viewing list of datapacks

### ISSUE THREAD

**Issue by seriousfreezing** [Adrenix/Nostalgic-Tweaks#73]
Minecraft Version: 1.20.4
Fabric Loader Version: 0.15.11
Fabric API Version: 0.97.1
Nostalgic Tweaks Version: 2.0.0-Beta-9.0-RC

The error occurs when adding the "ImmediatelyFast" mod and activating in its settings the option: "experimental_screen_batching":true
If you don't activate this option, it will appear normally.

https://paste.atlauncher.com/view/cceb121f-7a1d-45e3-a20f-a0a879df2485
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/66693072/3c796b35-6684-462a-b5d0-cf355800854c)

**Comment by Adrenix** [comment]
I use Architectury's tooltip events to modify the tooltip background. I don't modify tooltip text in any way. So it might be a conflict with ImmediatelyFast and Architectury? Also note that ImmediatelyFast has marked this as an "experimental" setting, so I recommend leaving it off to prevent this issue. To add on to this, missing text also seems to happen with all tooltips rendered from the chat screen.

**Comment by seriousfreezing** [comment]
I'm aware of the experimental status, but do you think I should pass this bug on to ImmediatelyFast or Architectury?

**Comment by Adrenix** [comment]
This might be an issue with ImmediatelyFast, and possibly related to [this](https://github.com/RaphiMC/ImmediatelyFast/issues/217)?

**Comment by seriousfreezing** [comment]
I have to believe it could be something related, I'll follow this thread and see what's done.
