### ISSUE TITLE
[FABRIC] Sodium 0.6 crash on world join with "Old Water Lighting" enabled

### ISSUE THREAD

**Issue by helpimnotdrowning** [Adrenix/Nostalgic-Tweaks#74]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.1
Fabric Loader Version: 0.15.11
Fabric API Version: 0.92.2+1.20.1
Nostalgic Tweaks Version: 2.0.0-Beta-8.4.1
Sodium Version: 0.6.0-alpha.2 (via Iris Discord server, [message link](https://discord.com/channels/774352792659820594/883067831485366304/1260083890127634455) )

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

Minecraft crashes when joining a world with Iris' Sodium 0.6 alpha 2 build when "Old Water Rendering" is enabled

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

https://gist.github.com/helpimnotdrowning/4dd1b605f937480a3bb7dfccd6fa0ae4

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

n/a

## Notes
![image](https://github.com/Adrenix/Nostalgic-Tweaks/assets/35247379/da840498-34d0-4e9c-b721-1d3fe0aad8d5)

As mentioned by IMS in the Iris 1.8 alpha 3 support thread, the Sodium method `net.caffeinemc.mods.sodium.client.world.LevelSlice.method_22336` (`getLightEngine`) is called [here, in Nostalgic Tweaks](https://github.com/Adrenix/Nostalgic-Tweaks/blob/fd4878084d1c718e2dc7fe0963141eff4d8ed4a0/common/src/main/java/mod/adrenix/nostalgic/util/common/WorldCommonUtil.java#L39), instead of the vanilla `net.minecraft.world.level.BlockAndTintGetter.getLightEngine` (for some reason?), [which will only throw UnsupportedOperationException](https://github.com/CaffeineMC/sodium-fabric/blob/db7c77a0960c166e4177acbbabd892167fcd0271/src/main/java/net/caffeinemc/mods/sodium/client/world/LevelSlice.java#L263C1-L267C1), which kills the game.

**Comment by Adrenix** [comment]
Beta 9 is now version locked to Sodium 0.5.x. An update will be needed to support Sodium 0.6.x.

**Comment by helpimnotdrowning** [comment]
Great, that's fine!
