### ISSUE TITLE
[FABRIC] Player name tags don't render when "Old Name Tags" option is turned on

### ISSUE THREAD

**Issue by nenamoree9** [Adrenix/Nostalgic-Tweaks#75]
Minecraft Version: 1.21
Fabric Loader Version: 0.15.11-1.21
Fabric API Version: 0.100.6
Nostalgic Tweaks Version: 2.0.0 Beta 9

This is not working as intended. Normally, player name tags with this option when rendered far away, are more bigger and when closer, it's smaller.

When I installed this update, I was playing in multiplayer but the name tags didn't render.

![bug](https://github.com/user-attachments/assets/f216fe19-53e0-42ea-b60a-b1b807d401a2)

**Comment by Adrenix** [comment]
Fixed in beta 901. Thanks for submitting this issue!
