### ISSUE TITLE
[FABRIC] Conflict with sky mods

### ISSUE THREAD

**Issue by VindSole** [Adrenix/Nostalgic-Tweaks#76]
## Version Information
Minecraft Version: 1.21
Fabric Loader Version: 0.16.0
Fabric API Version: 0.100.6+1.21
Nostalgic Tweaks Version: 2.0.0-beta.900

## Describe the Bug
Nostalgic Tweaks seems to be conflicting with sky mods such as [Astrocraft](https://modrinth.com/mod/astrocraft) even when all or relevant tweaks are disabled,

Crashlog: "N/a"

## Bug Context
Stars become less bright when Astrocraft is installed, old stars tweak is set to "Modern", which should yield no changes from vanilla, only fix is to disable the mod in the config menu or remove the mod entirely.

## Screenshots
![image](https://github.com/user-attachments/assets/ddc6e51c-0512-44c5-8782-75bbef2201de)

![image](https://github.com/user-attachments/assets/3bcf8dda-378d-4d59-8186-c7717940e531)

**Comment by Adrenix** [comment]
Fixed in beta 901. Thanks for submitting this issue!
