### ISSUE TITLE
[FABRIC] Critting doesn't work even when enabled

### ISSUE THREAD

**Issue by Glinckey** [Adrenix/Nostalgic-Tweaks#77]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.21
Fabric Loader Version: 0.15.11
Fabric API Version: 0.100.7+1.21
Nostalgic Tweaks Version: 2.0.0-beta.901

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

The crit animation and sound don't work even when the setting is enabled

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

N/A

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

N/A

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by Adrenix** [comment]
There are separate client-side tweaks that are not connected to the server-side critical hit tweak. To get the critical hit particles, turn `Eye Candy > Particle Candy > Attack Particles > Disable Critical Hit Particles` to `No`. To get the critical hit sounds, turn `Sound > Damage Sounds > Disable Attack Sounds` to `No`. Also ensure that you do not have a resource pack enabled that removes the sounds or particles.

**Comment by Glinckey** [comment]
Yeah, that worked, thank you! and sorry for the annoyance.

**Comment by Adrenix** [comment]
No worries, this was not an annoyance! I'm glad that this was just a misconfiguration and not a code issue on my part. :)
