### ISSUE TITLE
[FABRIC] Swimming out of water while still holding the sprint key allows sprinting even with "Prevent Sprinting : Yes"

### ISSUE THREAD

**Issue by bobbybobbinsons** [Adrenix/Nostalgic-Tweaks#78]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.21
Fabric Loader Version: 0.16.0
Fabric API Version: 0.100.7
Nostalgic Tweaks Version: 2.0.0-beta.901

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

Swimming ("Prevent Swimming : No" ) out of the water into land while holding the sprint/swim button allows sprinting on land even with "Prevent Sprinting : Yes"

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

N/a

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

"Prevent Sprinting : Yes" but ""Prevent Swimming : No"

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by Adrenix** [comment]
Fixed in beta 902/903. Thank you for submitting this!
