### ISSUE TITLE
[FABRIC] Always Aggressive Iron Golems

### ISSUE THREAD

**Issue by Ampmau** [Adrenix/Nostalgic-Tweaks#79]
Version Information
1.21
Minecraft Version: 1.21
Fabric Loader Version: 0.16.0
Fabric API Version: 0.100.7+ 1.21
Nostalgic Tweaks Version: V2.0.0-beta.901
 The Bug:
Iron Golem attacking me without me hitting it at all, there was no crash, I did open LAN to turn off universal anger to see if that fixed it, no it did not, it kept doing it, I did not punch a villager at all, and it doesn't matter if it is one i killed or it respawned, it, they I should say they keep attacking me. 
## Crash Report
There was no crash just annoying rouge iron golems
## Bug Context
Bug context is the iron golem killing me as it respawns. And they almost act like ender man when I look at them they get mad?? 
## Screenshots
![2024-07-23_01 03 42](https://github.com/user-attachments/assets/c015f142-4f51-42b4-93e2-efbd2bac7d10)
![2024-07-23_01 03 41](https://github.com/user-attachments/assets/2345fd38-edac-4429-b0d2-d236fc30c4fe)
https://github.com/user-attachments/assets/99232a9c-3bfb-476c-98b8-54cd8bb045a7
Soul help me it did it again, had to  go in peaceful so i couldn't hurt me

**Comment by Adrenix** [comment]
I can't reproduce this behavior. Do you have any other mods installed?
