### ISSUE TITLE
[FABRIC] Crashing on startup with BetterNether installed

### ISSUE THREAD

**Issue by Kaede4Life** [Adrenix/Nostalgic-Tweaks#8]
Hi, I am experiencing a startup crash with Nostalgic Tweaks when BetterNether (https://www.curseforge.com/minecraft/mc-mods/betternether) is installed. I have included two different crash reports, as the game displayed a crash report for both BetterNether and Nostalgic Tweaks, and they seem to be related.

Nostalgic Tweaks:
https://gist.github.com/Kaede4Life/42af51e7d11e7f81aa3e58bfff8d9bc9

BetterNether:
https://gist.github.com/Kaede4Life/63b0d8d970bef5c5d7a9321cd2f43c0c

**Comment by Adrenix** [comment]
Thank you for submitting this! I am currently focused on fixing crashes and compatibility issues for the next update so the hope is to have this resolved in a update coming very soon. 👍

**Comment by Adrenix** [comment]
This issue is now fixed in v1.0.3.
