### ISSUE TITLE
[FABRIC] Remove Mipmap Texturing feature enabled on every startup, even when set to disabled

### ISSUE THREAD

**Issue by VeggeieDude** [Adrenix/Nostalgic-Tweaks#80]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.1
Fabric Loader Version: 0.15.11
Fabric API Version: 0.92.2
Nostalgic Tweaks Version: 2.0.0-beta.902

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

I have "Remove Mipmap Texturing" set on disabled, and the config will save but every time I turn off Minecraft and start it back up, the Remove Mipmap Texturing feature will be enabled, even if it says "No". I have to turn it back on, then off again to fix it every start up.

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

REPLACE ME WITH A PASTE CRASH LINK HERE (or just put "N/a")

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

REPLACE ME WITH CONTEXT HERE (or just put "N/a")

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by VOLKOUL** [comment]
I came here to report the same thing haha! The only difference is that I use NeoForge 1.20.1, so both modloaders are affected.

**Comment by Adrenix** [comment]
Fixed in beta 903. Thank you for submitting this!
