### ISSUE TITLE
[SHADERS] north sunrise incompatible with some shaders

### ISSUE THREAD

**Issue by Barerock** [Adrenix/Nostalgic-Tweaks#83]
## Version Information
Minecraft Version: 1.20.1
Forge Version: 47.3.5
Nostalgic Tweaks Version: 2.0.0 B-8.4.1

## Describe the Bug
Shader moon/sun light does not follow where the sun/moon is ingame. Most visible with Rethinking Voxels.

## Bug Context
The North sunrise option disconnects the actual moon position. Shaders follow the moon position, so they should be able to follow, but this mod or Iris have an issue with the option, preventing the shader from detecting the moon/sun position

## Screenshots
![2024-08-05_15 44 34](https://github.com/user-attachments/assets/b07367e5-a807-4060-92ac-ce844542a6eb)

**Comment by Adrenix** [comment]
As far as I know, this is not something that I can fix. I recommend updating the mod to beta 9 for better mod support, performance, and more tweaks. In beta 9, set the `Old Sunrise at North` in `Eye Candy > World Candy > Sky Candy` to `No` to fix this.

**Comment by Barerock** [comment]
That's exactly what I did. Thanks for the mod <3
