### ISSUE TITLE
[FABRIC] Crashes when entering world.

### ISSUE THREAD

**Issue by zaidenCo** [Adrenix/Nostalgic-Tweaks#85]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.21
Fabric Loader Version: 0.15.11
Fabric API Version: 0.101.2+1.21
Nostalgic Tweaks Version: 2.0.0-beta.901

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

When joining my 1.21 world, it crashes. It doesn't crash on other worlds, but I know nothing is wrong with the world, it works fine without the mod. I'm also not currently holding or wearing anything.

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

[REPLACE ME WITH A PASTE CRASH LINK HERE (or just put "N/a")](https://gist.github.com/zaidenCo/f657e70e0f2ce2c52870f7b4a65c365c)

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

the crash happens after the loading world screen is finished.

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by Adrenix** [comment]
Thank you for submitting this! I just released beta.904 which is a hotfix for this crash on Fabric. Make sure to update your Fabric API to 0.102.0 or greater.
