### ISSUE TITLE
disabling dirt background enables panorama even if it's disabled by another mod

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Adrenix/Nostalgic-Tweaks#86]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.21
Quilt Loader Version: 0.26.3
QFAPI Version: 11.0.0-alpha.3+0.100.7-1.21
Nostalgic Tweaks Version: 2.0.0-beta.903 (latest doesn't work on 1.21 because it requires a 1.21.1 version of fabric api/qfapi, and i can't update because mods wouldn't be supported)

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

disabling the dirt background causes the main menu to use the vanilla panorama even if it's replaced by another mod

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

n/a

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

n/a

## Screenshots
> If applicable, add screenshots to help explain your problem.
![title screen](https://github.com/user-attachments/assets/3ac070a9-25df-4fc8-a311-1aa79b297877)
![help and options](https://github.com/user-attachments/assets/8eabdef7-a728-45bc-b6b7-f7c9833f764a)

**Comment by Adrenix** [comment]
This is a problem with the other mod. N.T's title screen calls the vanilla screen menu background when the old dirt overlay is disabled. The other mod must properly override the vanilla menu background for it to show up on our title screen.
