### ISSUE TITLE
[FORGE] Incompatibility with immersive engineering

### ISSUE THREAD

**Issue by HumanF91R** [Adrenix/Nostalgic-Tweaks#89]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.19.2
Forge Version: 43.4.0
Nostalgic Tweaks Version: 2.0 beta 8.4

## Describe the Bug
> Using bucket on metal barrel either putting in or taking out creosote causes game crash

REPLACE ME WITH A DESCRIPTION

## Crash Report
> https://gist.github.com/HumanF91R/6b812c094b66d02178cdf561df68bf9c

**Comment by forkiesassds** [comment]
Nostalgic Tweaks is no longer supports anything older than 1.20.
