### ISSUE TITLE
[FORGE] crash on world creation and unable to join existing worlds

### ISSUE THREAD

**Issue by Quadruplay** [Adrenix/Nostalgic-Tweaks#95]
## Version Information
> Please fill out the following information. Replace each `x` with a number:

Minecraft Version: 1.20.1
Forge Version: 47.3.5
Nostalgic Tweaks Version: 2.0.0-beta.902

## Describe the Bug
> A clear and concise description of what the bug is (e.g., startup crash, runtime crash, or something not working as intended).

Unable to join existing worlds, and crashing when attempting to make a new one

## Crash Report
> If applicable, please include a link to a complete crash report. You can use Gist (https://gist.github.com) to create this link. These reports can be found in `.minecraft/crash-reports`.

[crash-2024-09-27_13.34.47-client.txt](https://github.com/user-attachments/files/17163524/crash-2024-09-27_13.34.47-client.txt)

## Bug Context
> If applicable, add some context to the bug. If a crash occurred while you were in-game, what happened before the crash? For example, "I fell from a high place and before the hurt sound could play the game crashed."

REPLACE ME WITH CONTEXT HERE (or just put "N/a")

## Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by Adrenix** [comment]
I'd need the full game logs to know what exactly is going wrong. This might have something to do with a datapack. If you're still crashing then please re-open this issue with the full game-logs prior to crashing.
