### ISSUE TITLE
[FABRIC] Game Crashes on Launch

### ISSUE THREAD

**Issue by autumnly24** [Adrenix/Nostalgic-Tweaks#99]
Minecraft Version: 1.20.1
Fabric Loader Version: 0.16.7
Fabric API Version: 0.92.2
Nostalgic Tweaks Version: 2.0.0-beta.903

I've tried launching the game, and whenever I do, it crashes with an error before anything starts even loading. I've tried downgrading the fabric loader version, downgrading the Nostalgiac Tweaks version, everything I could feasibly think of. It says it's an error with Porting Lib.

[crash-2024-11-24_08.17.28-client.txt](https://github.com/user-attachments/files/17893419/crash-2024-11-24_08.17.28-client.txt)

**Comment by forkiesassds** [comment]
Incompatibility with Porting Lib it seems, try disabling the Carcass mod.

**Comment by Adrenix** [comment]
Running latest Porting Lib on its own doesn't crash for me, so this is probably a problem with the Carcass mod. Their mod is closed source, so identifying the problem on our end is not feasible. As mentioned, I'd recommend removing the Carcass mod until they update with a fix.
